name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v2
        with:
          submodules: true
          # NOTE - if LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Generate project files
        run: tools/premake5 vs2019

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/iw6x.sln

      - name: Upload ${{matrix.configuration}} binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            build/bin/**/*.exe
            build/bin/**/*.dll

      - name: Upload ${{matrix.configuration}} debug symbols
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}} debug symbols
          path: |
            build/bin/**/*.pdb

      - name: Post CI status notification to Discord
        uses: sarisia/actions-status-discord@v1.7.1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_CI_BOT_WEBHOOK }}
          title: "${{matrix.configuration}} Build"
